# This is the configuration used to check the rubocop source code.
AllCops:
  Include:
    - Gemfile
    - Rakefile
    - bin/*
    - github_copier.gemspec
    - lib/**/*.rb
    - test/**/*.rb
    - spec/**/*.rb
